### ISSUE TITLE
The Delete won't work

### ISSUE THREAD

**Issue by jiak94** [jiak94/PersonalLibrary#1]
With selected a book on the left, and hit Delete, the system throw a exception.

Caused by: java.lang.UnsupportedOperationException
    at java.util.AbstractList.remove(AbstractList.java:161)
    at library.view.BookOverviewController.handleDeleteBook(BookOverviewController.java:177)
    ... 57 more

**Comment by jiak94** [comment]
Now fixed. Delete the selected book directly from the bookData list.
